version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck # Check for unchecked errors (enabled by default)
    - govet # Reports suspicious constructs (enabled by default)
    - ineffassign # Detect ineffectual assignments (enabled by default)
    - staticcheck # Advanced Go linter (enabled by default)
    - unused # Check for unused constants, variables, functions and types (enabled by default)
    - misspell # Spell checker
    - gocritic # Opinionated linter
    - unparam # Report unused function parameters
    - unconvert # Remove unnecessary type conversions
    - gosec # Security-focused linter
    - bodyclose # Check for HTTP response body close
    - nilerr # Find code that returns nil even if it checks err != nil
    - noctx # Find sending HTTP request without context.Context
    - nilnil # Check that nil is not returned if error is returned

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow # Can be too noisy for some codebases

  staticcheck:
    checks: ["all"]

  gosec:
    excludes:
      - G404 # Use of weak random number generator - not security critical for this use case

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - unparam

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
